### ISSUE TITLE
xcb/xcb_keysyms.h: No such file or directory

### ISSUE THREAD

**Issue by joshhartigan** [dcat/swm#1]
Apologies for noob question.

I'm trying to compile this wm on Crunchbang, and upon running `make` I get the error in the header of this issue. I've tried installing some libraries via `apt-get`, but obviously not the right ones.

**Comment by Ishidres** [comment]
> Search for something like "libxcb-keysym" or alike.

Thanks! Installing `libxcb-keysyms1-dev` solved the issue. :grinning:

**Comment by dongshengLiu** [comment]
> 

Sloved my problem too. Thans!
