### ISSUE TITLE
Focus on follow not working

### ISSUE THREAD

**Issue by jonlorusso** [dcat/swm#11]
Focus on follow appears to be enabled by default in config.h:

    #define ENABLE_SLOPPY

but does not seem to working.  Is there anything additional I need to do in order to get this to work?

**Comment by dcat** [comment]
Can you elaborate on what happens/doesn't happen?

**Comment by moeenn** [comment]
I'm not able to move the Windows using modkey+right click

The focus also seems to change randomly. 

-----Original Message-----

**Comment by jonlorusso** [comment]
I am only only able to focus a window by using focus.sh (from contrib). Super + click was working but is no longer. I am my sure what change (likely something in my .xinitrc) broke that.

**Comment by dcat** [comment]
just a stab in the dark, but is scroll lock, caps lock, or num lock active?

activating any of the locks causes swm key management to break

**Comment by dcat** [comment]
I finally got a hold of a computer running x11, I made a booboo in the config.h.

Thank you for letting me know.
