### ISSUE TITLE
swm not aware of windows created before it was started.

### ISSUE THREAD

**Issue by jonlorusso** [dcat/swm#13]
I was still seeing issues with focus on follow as well as click to focus/move/resize.

I added some debug to swm.c and started it directly from a console (rather than via lightdm, etc.)  It seems that swm is not aware of any windows that were started prior to starting swm.   Unmapping and re-mapping those windows does not seem to help.

**Comment by dcat** [comment]
yes, will only handle windows that are created after swm has been run. (this is by design)
