### ISSUE TITLE
Cursor invisible on startup

### ISSUE THREAD

**Issue by MehLON** [dcat/swm#14]
The cursor is invisible for me when I start swm with xinit. Launching `lxappearance` fixes this for the session. Any way I can make this happen automatically?

**Comment by MehLON** [comment]
I've just figured a hack, though doing it without hacks would be nicer
```
# silly hack for initializing cursor
(
	lxappearance&
	while [ ! -n "$(lsw)" ]; do sleep 0.02; done
	kill $!
)
```

**Comment by dcat** [comment]
swm doesn't do anything to the cursor, you can set the cursor using `xsetroot`

if you're interested, I [ported osx's aqua pointer to X11](https://gist.github.com/dcat/dd80fe04383ce0954f6c)

**Comment by MehLON** [comment]
Didn't know `xsetroot` could do that. Thanks.
